spring.application.name=parmy_backend

# Server Configuration
server.port=${PORT:8080}
server.forward-headers-strategy=framework

# MongoDB Configuration
#mongodb+srv://studentsboatpdx:J8yMphsSMXxyMET1@triviocluster.2ohj6vq.mongodb.net/trivio_db?retryWrites=true&w=majority&appName=TrivioCluster
spring.data.mongodb.uri=mongodb+srv://parmy:parmy%40123@cluster0.rela60y.mongodb.net/parmywebsite?retryWrites=true&w=majority&appName=Cluster0
# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=parmydevelopment.in@gmail.com
spring.mail.password=dilzgfzybtgkgmcv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
#spring.mail.properties.mail.debug=true



# JWT Configuration
jwt.secret=mkZoXlqK0jhhiH9hx+X1AXSX35sSa9IcNrLUn3nNJnNyHJM/2oMf1E8JBTGtnDf9Te9En2kAFr9a91AN2WZ2hQ==
jwt.expiration=3600000

# CORS Configuration
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:3000,https://parmytechnologies.netlify.app}

# File Upload Configuration
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# Logging
logging.level.com.trivio=DEBUG
logging.level.org.springframework.security=DEBUG

# OAuth2 Google Client
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:}

